services:
  ubpa-hermes: 
    image: ubpa-hermes:latest
    ports:
      - "8080:8080"
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "12345"

    volumes:
      - ./config.json:/config.json:ro
